highlighter: rouge
permalink: ./:title
title: "Weak Notes"
description: "// A working in public, second brain"
owner:
  name: thechelsuk
  email: "feedback@thechels.uk"
  uri: https://thechels.uk
  avatar: "/.well-known/avatar.png"
url: https://thechels.uk
encoding: UTF-8
future: false
github:
  repository_url: https://github.com/thechelsuk/uk.thechels
  branch: main
sass:
  style: compressed
plugins:
  - jekyll-avatar
  - jekyll-github-metadata
exclude:
  - CNAME
  - README.md
  - LICENSE.md
  - SECURITY.md
  - requirements.txt
  - _python/
  - .github/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
include:
  - ".well-known"
  - "_pages"

# Site Navigation
## Header
navigation_header:
  - link: "/about"
    title: "About"
  - link: "/slashes"
    title: "Pages"
  - link: "https://links.thechels.uk"
    title: "Links &#11084;"
  - link: "https://tools.thechels.uk"
    title: "Tools &#11084;"
  - link: "https://shop.thechels.uk"
    title: "Shop &#11084;"
## SubMenu
navigation_data:
  - link: "/feeds"
    title: "Feeds"
  - link: "/books"
    title: "Books"
  - link: "/teams"
    title: "Live Teams"
  - link: "/podcasts"
    title: "Podcasts"
  - link: "/blogroll"
    title: "Blogroll"
  - link: "/films"
    title: "Films"
  - link: "/constraints"
    title: "Constraints"
  - link: "/sitemap"
    title: "Sitemap"
## SubMenu
navigation_slashes:
  - link: "/ai"
    title: "AI"
  - link: "/apps"
    title: "Apps"
  - link: "/about"
    title: "About"
  - link: "/architecture"
    title: "Architecture"
  - link: "/.well-known/avatar.png"
    title: "Avatar"
  - link: "/about#colophon"
    title: "Colophon"
  - link: "/cv"
    title: "CV"
  - link: "/disability"
    title: "Disability"
  - link: "/green"
    title: "Green"
  - link: "/manual"
    title: "Manual"
  - link: "/now"
    title: "Now"
  - link: "/pgp"
    title: "PGP key"
  - link: "/.well-known/privacy.txt"
    title: "Privacy"
  - link: "/projects"
    title: "Projects"
  - link: "/save"
    title: "Save"
  - link: "/.well-known/security.txt"
    title: "Security"
  - link: "/style"
    title: "Style Guide"
  - link: "/uses"
    title: "Uses"
  - link: "/verify"
    title: "Verify"
  - link: "/indieweb.txt"
    title: "IndieWeb"
## Footer links
navigation_footer:
  - link: "/feed.xml"
    title: "RSS"
  - link: "/feed.json"
    title: "JSON"
  - link: "/humans.txt"
    title: "Humans"
  - link: "/robots.txt"
    title: "Robots"
  - link: "/llms.txt"
    title: "LLMs"
  - link: "/sitemap.xml"
    title: "Sitemap"
  - link: "/.well-known/privacy.txt"
    title: "Privacy"
  - link: "/.well-known/security.txt"
    title: "Security"
  - link: "https://bsky.app/profile/thechels.uk"
    title: "Bluesky"
  - link: "https://mastodon.social/@Thechelsuk"
    title: "Mastodon"
