highlighter: rouge
permalink: ./:title
title: "Weak Notes"
description: "// A working out loud, public second brain"
author: "Mat"
url: https://thechels.uk
copyright: "MB"
encoding: UTF-8
future: false
repository: Mat-0/TheChels.uk
defaultImagePath: "/images/splashscreens/apple-touch-icon-180x180.png"
github:
  repository_url: https://github.com/Mat-0/TheChels.uk
  branch: main
sass:
  style: compressed
plugins:
  - jekyll-feed
  - jekyll-avatar
  - jekyll-github-metadata
exclude:
  - CNAME
  - README.md
  - LICENSE.md
  - SECURITY.md
  - requirements.txt
  - _python/
  - .github/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
include:
  - ".well-known"
  - "_pages"

# Site Navigation
## Header
navigation_header:
  - link: "/about"
    title: "About"
  - link: "/slashes"
    title: "Pages"
  - link: "https://links.thechels.uk"
    title: "Links &#11084;"
  - link: "https://tools.thechels.uk"
    title: "Tools &#11084;"
  - link: "https://shop.thechels.uk"
    title: "Shop &#11084;"
## SubMenu
navigation_data:
  - link: "/books"
    title: "Books"
  - link: "/teams"
    title: "Live Teams"
  - link: "/podcasts"
    title: "Podcasts"
  - link: "films"
    title: "Films" 
  - link: "/constraints"
    title: "Constraints"
## SubMenu
navigation_slashes:
  - link: "/projects"
    title: "Apps"
  - link: "/about"
    title: "About"
  - link: "/architecture"
    title: "Architecture"
  - link: "/.well-known/avatar.png"
    title: "Avatar"
  - link: "/about#colophon"
    title: "Colophon"
  - link: "/cv"
    title: "CV"
  - link: "/feed"
    title: "Feed"
  - link: "/green"
    title: "Green"
  - link: "/manual"
    title: "Manual"
  - link: "/now"
    title: "Now"
  - link: "/pgp"
    title: "PGP key"
  - link: "/.well-known/privacy.txt"
    title: "Privacy"
  - link: "/projects"
    title: "Projects"
  - link: "/save"
    title: "Save"
  - link: "/.well-known/security.txt"
    title: "Security"
  - link: "/sitemap"
    title: "Sitemap"
  - link: "/style"
    title: "Style Guide"
  - link: "/uses"
    title: "Uses"
  - link: "/verify"
    title: "Verify"
  - link: "/indieweb.txt"
    title: "IndieWeb"
## Footer links
navigation_footer:
  - link: "/feed"
    title: "RSS"
  - link: "/sitemap.xml"
    title: "Sitemap"
  - link: "/humans.txt"
    title: "Humans"
  - link: "/robots.txt"
    title: "Robots"
  - link: "/.well-known/privacy.txt"
    title: "Privacy"
  - link: "/.well-known/security.txt"
    title: "Security"
