---
name: Add Slogan
on:
    issues:
        types: [labeled, edited]
jobs:
    Validation:
        if: contains( github.event.issue.labels.*.name, 'slogans')
        runs-on: ubuntu-latest
        steps:
            - name: Echo
              run: echo "Check complete"
    Execution:
        name: Runner
        uses: ./.github/workflows/runner.yml
        needs: Validation
        with:
            content: ${{ github.event.issue.body }}
            label: "slogans"
    Deploy:
        needs: Execution
        uses: ./.github/workflows/deploy.yml
        secrets: inherit
