---
name: Add Offers
on:
  issues:
    types: [labeled, edited]
jobs:
  Validation:
    if: contains( github.event.issue.labels.*.name, 'offers')
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "Check complete"
  Execution:
    name: Runner
    uses: ./.github/workflows/block-runner.yml
    needs: Validation
    with:
      content: ${{ github.event.issue.body }}
      label: "offers"
  Deploy:
    needs: Execution
    uses: ./.github/workflows/deploy.yml
    secrets: inherit