---
name: Add Book
on:
    workflow_dispatch:
        inputs:
            isbn:
                description: "ISBN"
                required: true
env:
    actor: ${{ github.actor }}
    owner: ${{ github.repository_owner }}
    github_token: ${{ secrets.GITHUB_TOKEN }}
jobs:
    Build:
        runs-on: ubuntu-latest
        if: ${{ github.actor == github.repository_owner }}
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                  python-version: 3.13.1

            - uses: actions/cache@v5
              name: Configure pip caching
              with:
                  path: ~/.cache/pip
                  key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
                  restore-keys: |
                      ${{ runner.os }}-pip-

            - name: Install Python dependencies
              run: |
                  python -m pip install -r "./_python/requirements.txt" --quiet

            - name: Run add_film script
              run: |
                  python '_python/add_book.py' --isbn "${{ inputs.isbn }}"

            - name: Commit and Push
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add -A && git commit -m "Added ${{ inputs.ISBN }}"
                  git push

    Deploy:
      needs: Build
      uses: ./.github/workflows/deploy.yml
      secrets: inherit
