---
name: Add Film
on:
    repository_dispatch:
    workflow_dispatch:
        inputs:
            title:
                description: "title"
                required: true
            rating:
                description: "rating"
                required: true

concurrency:
    group: add-film
    cancel-in-progress: false

env:
    actor: ${{ github.actor }}
    owner: ${{ github.repository_owner }}
    github_token: ${{ secrets.GITHUB_TOKEN }}
    omdb_key: ${{ secrets.OMDB_API_KEY }}

jobs:
    Build:
        name: Builder
        if: ${{ github.actor == github.repository_owner }}
        runs-on: macOS-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6
            - name: Pull latest changes
              run: |
                  git pull origin main
            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                  python-version: 3.13.1
            - uses: actions/cache@v5
              name: Configure pip caching
              with:
                  path: ~/.cache/pip
                  key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
                  restore-keys: |
                      ${{ runner.os }}-pip-
            - name: Install Python dependencies
              run: |
                  python -m pip install -r "./_python/requirements.txt" --quiet
            - name: Run add_film script
              run: |
                  python '_python/add_film.py' --title "${{ inputs.title }}" --rating "${{ inputs.rating }}"
            - name: Commit and push
              run: |-
                  git diff
                  git config user.name "GitHub Action"
                  git config user.email "action@github.com"
                  git diff --quiet || (git add -A && git commit -m "${{ inputs.Title }} added to DB")
                  git push
