---
name: Daily Build and Deploy
on:
    workflow_dispatch:
    schedule:
        - cron: "5 8 * * *"
jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out Repo
              uses: actions/checkout@v6
              with:
                token: ${{ secrets.PAT_TOKEN }}
            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                  python-version: 3.13.1
            - uses: actions/cache@v5
              name: Configure pip Caching
              with:
                  path: ~/.cache/pip
                  key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
                  restore-keys: |
                      ${{ runner.os }}-pip-
            - name: Install Python Dependencies
              run: |
                  python -m pip install -r "./_python/requirements.txt" --quiet
            - name: Processing Python Scripts
              env:
                  OPEN_WEATHER_KEY: ${{ secrets.OPEN_WEATHER_KEY }}
                  OMDB_API_KEY: ${{ secrets.OMDB_API_KEY }}
              run: |-
                  python '_python/forecast.py'
                  python '_python/threat.py'
                  python '_python/task.py'
                  python '_python/doctrine.py'
                  python '_python/fixtures.py'
                  python '_python/stocks.py'
                  python '_python/wagnh.py'
                  python '_python/ftnews.py'
                  python '_python/word.py'
                  python '_python/quote.py'
                  python '_python/eno.py'
                  python '_python/remember_film.py'
                  python '_python/countdown.py'
                  python '_python/blogroll.py'
            - name: Commit and push
              run: |-
                  git diff
                  git config user.name "GitHub Action"
                  git config user.email "action@github.com"
                  COMMIT_MSG="New Daily Rundown $(date -u +%Y-%m-%dT%H:%M:%SZ)"
                  echo "COMMIT_MSG=$COMMIT_MSG" >> $GITHUB_ENV
                  git diff --quiet || (git add -A && git commit -m "$COMMIT_MSG")
                  git push
            - name: Log commit message
              run: |
                  echo "Committed: $COMMIT_MSG"
