---
name: Python CI
on:
    pull_request:
        paths:
            - "_python/*"
    push:
        paths:
            - "_python/*"
    workflow_dispatch:

jobs:
    python_testing:
        name: Python Testing
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.9", "3.10", "3.13.1"]
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v6
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install Python Dependencies
              run: python -m pip install -r "./_python/requirements.txt" --quiet
              working-directory: ./_python

            - name: Run Tests
              uses: pavelzw/pytest-action@v2
              with:
                  emoji: true
                  verbose: false
                  job-summary: true
                  report-title: "Test Report"
